services:
  - type: web
    name: concentration-analyzer
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /login
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_PATH
        value: database.db
      - key: MODEL_DIR
        value: model
      - key: PORT
        value: 10000
